// <auto-generated />
using System;
using ExamRegistrationService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamRegistrationService.Migrations
{
    [DbContext(typeof(ExamRegistrationContext))]
    partial class ExamRegistrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamRegistrationService.Entities.ExamRegistration", b =>
                {
                    b.Property<Guid>("ExamRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StudentCurrentSemester")
                        .HasColumnType("int");

                    b.Property<int>("StudentEnrolledYear")
                        .HasColumnType("int");

                    b.Property<string>("StudentFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubjectExamTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectSemester")
                        .HasColumnType("int");

                    b.Property<int>("SubjectTerm")
                        .HasColumnType("int");

                    b.HasKey("ExamRegistrationId");

                    b.ToTable("ExamRegistrations");

                    b.HasData(
                        new
                        {
                            ExamRegistrationId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            StudentCurrentSemester = 1,
                            StudentEnrolledYear = 1,
                            StudentFirstName = "Petar",
                            StudentId = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            StudentIndex = "IT1/2020",
                            StudentLastName = "Petrović",
                            SubjectCode = "S12020",
                            SubjectExamTime = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = new Guid("21ad52f8-0281-4241-98b0-481566d25e4f"),
                            SubjectName = "Subject 1",
                            SubjectSemester = 1,
                            SubjectTerm = 1
                        },
                        new
                        {
                            ExamRegistrationId = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            StudentCurrentSemester = 1,
                            StudentEnrolledYear = 2,
                            StudentFirstName = "Marko",
                            StudentId = new Guid("32cd906d-8bab-457c-ade2-fbc4ba523029"),
                            StudentIndex = "IT2/2019",
                            StudentLastName = "Marković",
                            SubjectCode = "S22020",
                            SubjectExamTime = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SubjectId = new Guid("9d8bab08-f442-4297-8ab5-ddfe08e335f3"),
                            SubjectName = "Subject 2",
                            SubjectSemester = 2,
                            SubjectTerm = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
